merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/', views.band_list, name='band-list'),
    path('about-us/', views.about),
    path('contact/', views.contact),
    path('listings/<int:id>', views.listings_detail, name='listing-detail'),
    path('listings/', views.listings_list, name='listing-list'),
]

listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator



class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        
    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return self.name
    


class Listing(models.Model):
    class Type(models.TextChoices):
        RECORDS = 'REC'
        CLOTHING = 'CLO'
        POSTERS = 'POS'
        MISC = 'MISC'
        
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=200)
    sold = models.fields.BooleanField(default=True)
    year = models.fields.IntegerField()
    types = models.fields.CharField(choices=Type.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)
    
    def __str__(self):
        return self.title
    
    

listings/views.py
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band
from listings.models import Listing

def band_list(request):
    bands = Band.objects.all()
    return render(request,
                  'listings/band_list.html',
                  {'bands': bands})
def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_detail.html',
                  {'band': band})  


def listings_list(request):
    listings = Listing.objects.all()
    return render(request, 
                  'listings/listing_list.html',
                  {'listings': listings})
def listings_detail(request, id):
    listings = Listing.objects.get(id=id)
    return render(request,
                  'listings/listing_detail.html',
                  {'listings': listings})




def about(request):
    return render(request, 
                  'listings/about.html')

def contact(request):
    return render(request, 
                  'listings/contact.html')

listings/templates/listings/about.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>À propos</h1>
<p>Nous adorons merch !</p>

{% endblock %}

listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ band.name }}</h2>

<ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Année de formation : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active|yesno }}</li>
    {% if band.official_homepage %}
    <li><a href="{{ band.official_homepage }}">{{band.official_homepage }}</a></li>
    {% endif %}
</ul>

<p>{{ band.biography }}</p>
<a href="{% url 'band-list' %}">Retour à la liste des groupes</a>

{% endblock %}

listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Groupes</h1>

<ul>
    {% for band in bands %}
    <li><a href="{% url 'band-detail' band.id  %}">{{ band.name }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

listings/templates/listings/base.html
{% load static %}

<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    </head>
    <body>

    <nav>
        <a href="{% url 'band-list' %}">Groupes</a>
        <a href="{% url 'listing-list' %}">Articles</a>
    </nav>    

        {% block content%}{% endblock %}

    </body>
</html>

listings/templates/listings/contact.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Contactez-nous</h1>
<a href="mailto:maxime@nukleon.fr">Envoyer un mail</a>

{% endblock %}

listings/templates/listings/hello.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Hello Django !</h1>
<h2>Les {{ bands|length }} groupes du moment :</p>
<ul>
    {% for band in bands %}
    <li>
        {{ band.name }}
    </li>
    {% endfor %}
</ul>

{% endblock %}

listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}
{% block content %}
<h2>{{ listings.title }}</h2>

<ul>
{% if listings.band %}
    <li>Groupe : {{ listings.band }}</li>
{% endif %}
    <li>Type : {{ listings.get_types_display }}</li>
    <li>Année  : {{ listings.year }}</li>
    <li>En vente : {{ listings.sold|yesno }}</li>
{% if listings.description %}
    <li>{{ listings.description }}</li>
{% endif %}
</ul>

<a href="{% url 'listing-list' %}">Retour à la liste des articles"</a>


{% endblock %}

listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Articles</h1>

<ul>
    {% for listing in listings %}
    <li><a href="{% url 'listing-detail' listing.id  %}">{{ listing.title }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

listings/templates/listings/listings.html
{% extends 'listings/base.html' %}
{% block content %}

<h1>Hello Django !</h1>
<h2>Les {{ listings|length }} articles du moment :</p>
<p>
    <ul>
        {% for listing in listings %}
        <li>{{ listing.title }}</li>
        {% endfor %}
    </ul>
</p>

{% endblock %}